name: deepsurvk
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - argh=0.26.2=py37_0
  - argon2-cffi=20.1.0=py37hcc03f2d_2
  - astroid=2.4.2=py37_0
  - async_generator=1.10=py37h28b3542_0
  - atomicwrites=1.4.0=py_0
  - autopep8=1.5.4=py_0
  - backcall=0.2.0=py_0
  - bcrypt=3.2.0=py37he774522_0
  - brotlipy=0.7.0=py37he774522_1000
  - bump2version=1.0.1=pyh9f0ad1d_0
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py37h03978a9_0
  - cffi=1.14.3=py37h7a1dbc1_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=py_0
  - cryptography=3.1.1=py37h7a1dbc1_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=py_0
  - entrypoints=0.3=py37_0
  - flake8=3.8.4=py_0
  - future=0.18.2=py37_1
  - icu=58.2=vc14hc45fdbb_0
  - idna=2.10=py_0
  - imagesize=1.2.0=py_0
  - importlib_metadata=2.0.0=1
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - isort=5.6.4=py_0
  - jedi=0.17.1=py37_0
  - jpeg=9b=vc14h4d7706e_1
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupytext=1.11.3=pyh6c4a22f_0
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h33f27b4_0
  - markdown-it-py=1.1.0=pyhd8ed1ab_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - notebook=6.4.0=py37haa95532_0
  - numpydoc=1.1.0=py_0
  - openssl=1.1.1k=h8ffe710_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.2=py37_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pluggy=0.13.1=py37_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.8=py_0
  - psutil=5.7.2=py37he774522_0
  - pycparser=2.20=py_2
  - pydocstyle=5.1.1=py_0
  - pylint=2.6.0=py37_0
  - pynacl=1.4.0=py37h62dcd97_1
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37ha878b3d_0
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h7840368_100_cpython
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.35.1=py_0
  - python_abi=3.7=1_cp37m
  - pywin32=227=py37he774522_1
  - pywin32-ctypes=0.2.0=py37_1001
  - pywinpty=1.1.1=py37h7f67f24_0
  - pyyaml=5.3.1=py37he774522_0
  - pyzmq=19.0.2=py37ha925a31_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.1=py_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - rope=0.18.0=py_0
  - rtree=0.9.4=py37h21ff451_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h03978a9_3
  - sip=4.19.24=py37ha925a31_0
  - sortedcontainers=2.2.2=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - spyder=4.1.5=py37_0
  - spyder-kernels=1.9.4=py37_0
  - sqlite=3.35.5=h8ffe710_0
  - terminado=0.10.1=py37h03978a9_0
  - testpath=0.4.4=py_0
  - tornado=6.0.4=py37he774522_1
  - traitlets=5.0.5=py_0
  - typed-ast=1.4.1=py37he774522_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ujson=4.0.1=py37ha925a31_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - watchdog=0.10.3=py37_0
  - wcwidth=0.2.5=py_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37h03978a9_1006
  - winpty=0.4.3=4
  - yaml=0.1.7=vc14h4cb57cf_1
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=ha925a31_3
  - zlib=1.2.11=vc14h1cdd9ab_1
  - pip:
    - absl-py==0.12.0
    - appdirs==1.4.4
    - astor==0.8.1
    - astunparse==1.6.3
    - attrs==21.2.0
    - autograd==1.3
    - autograd-gamma==0.5.0
    - babel==2.9.1
    - bleach==3.3.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - cycler==0.10.0
    - distlib==0.3.2
    - docutils==0.17.1
    - filelock==3.0.12
    - formulaic==0.2.3
    - gast==0.3.3
    - google-auth==1.31.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.38.0
    - h5py==2.10.0
    - importlib-metadata==1.7.0
    - interface-meta==1.2.3
    - jinja2==3.0.1
    - joblib==1.0.1
    - keras-preprocessing==1.1.2
    - keyring==22.3.0
    - kiwisolver==1.3.1
    - lifelines==0.26.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mccabe==0.6.1
    - more-itertools==8.8.0
    - numpy==1.18.0
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.4
    - pillow==8.2.0
    - pip==20.1.1
    - pkginfo==1.7.0
    - protobuf==3.17.3
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pydot==1.4.2
    - pyflakes==2.3.1
    - pygments==2.9.0
    - pytest==5.4.3
    - pytest-runner==5.2
    - python-graphviz==0.16
    - pytz==2021.1
    - readme-renderer==29.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rfc3986==1.5.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.4.1
    - seaborn==0.11.1
    - six==1.16.0
    - snowballstemmer==2.1.0
    - sphinx==3.1.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-serializinghtml==1.1.5
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.3.2
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - tox==3.18.0
    - tqdm==4.61.1
    - twine==3.2.0
    - urllib3==1.26.5
    - virtualenv==20.4.7
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - wheel==0.34.2
    - wrapt==1.12.1
    - zipp==3.4.1
prefix: C:\ProgramData\Anaconda3\envs\deepsurvk
